export const subjects = [
  "Maths",
  "English",
  "Biology",
  "Chemistry",
  "Account",
  "Physics",
  "Management",
];

export const states = [
  { stateId: "AB", name: "Abia" },
  { stateId: "AD", name: "Adamawa" },
  { stateId: "AK", name: "Akwa Ibom" },
  { stateId: "AN", name: "Anambra" },
  { stateId: "BC", name: "Bauchi" },
  { stateId: "BN", name: "Bornu" },
  { stateId: "BU", name: "Benue" },
  { stateId: "BY", name: "Bayelsa" },
  { stateId: "CR", name: "Cross River" },
  { stateId: "DT", name: "Delta" },
  { stateId: "ED", name: "Edo" },
  { stateId: "EK", name: "Ekiti" },
  { stateId: "EN", name: "Enugu" },
  { stateId: "EY", name: "Ebonyi" },
  { stateId: "FCT", name: "Abuja" },
  { stateId: "GM", name: "Gombe" },
  { stateId: "IM", name: "Imo" },
  { stateId: "JG", name: "Jigawa" },
  { stateId: "KB", name: "Kebbi" },
  { stateId: "KD", name: "Kaduna" },
  { stateId: "KG", name: "Kogi" },
  { stateId: "KN", name: "Kano" },
  { stateId: "KT", name: "Katsina" },
  { stateId: "KW", name: "Kwara" },
  { stateId: "LG", name: "Lagos" },
  { stateId: "NG", name: "Niger" },
  { stateId: "NS", name: "Nassarawa" },
  { stateId: "OD", name: "Ondo" },
  { stateId: "OG", name: "Ogun" },
  { stateId: "OS", name: "Osun" },
  { stateId: "OY", name: "Oyo" },
  { stateId: "PL", name: "Plateu" },
  { stateId: "RV", name: "Rivers" },
  { stateId: "SK", name: "Sokoto" },
  { stateId: "TR", name: "Taraba" },
  { stateId: "YB", name: "Yobe" },
  { stateId: "ZM", name: "Zamfara" },
];

export const lga = [
  { lgId: "AB1", name: "Aba North", stateId: "AB" },
  { lgId: "AB10", name: "Ohafia", stateId: "AB" },
  { lgId: "AB11", name: "Osisioma Ngwa", stateId: "AB" },
  { lgId: "AB12", name: "Ugwunagbo", stateId: "AB" },
  { lgId: "AB13", name: "Ukwa East", stateId: "AB" },
  { lgId: "AB14", name: "Ukwa West", stateId: "AB" },
  { lgId: "AB15", name: "Umuahia North", stateId: "AB" },
  { lgId: "AB16", name: "Umuahia South", stateId: "AB" },
  { lgId: "AB17", name: "Umu-Nneochi", stateId: "AB" },
  { lgId: "AB2", name: "Aba South", stateId: "AB" },
  { lgId: "AB3", name: "Arochukwu", stateId: "AB" },
  { lgId: "AB4", name: "Bende", stateId: "AB" },
  { lgId: "AB5", name: "Ikwuano", stateId: "AB" },
  { lgId: "AB6", name: "Isiala-Ngwa North", stateId: "AB" },
  { lgId: "AB7", name: "Isiala-Ngwa South", stateId: "AB" },
  { lgId: "AB8", name: "Isuikwuato", stateId: "AB" },
  { lgId: "AB9", name: "Obi Ngwa", stateId: "AB" },
  { lgId: "AD1", name: "Demsa", stateId: "AD" },
  { lgId: "AD10", name: "Madagali", stateId: "AD" },
  { lgId: "AD11", name: "Maiha", stateId: "AD" },
  { lgId: "AD12", name: "Mayo-Belwa", stateId: "AD" },
  { lgId: "AD13", name: "Michika", stateId: "AD" },
  { lgId: "AD14", name: "Mubi North", stateId: "AD" },
  { lgId: "AD15", name: "Mubi South", stateId: "AD" },
  { lgId: "AD16", name: "Numan", stateId: "AD" },
  { lgId: "AD17", name: "Shelleng", stateId: "AD" },
  { lgId: "AD18", name: "Song", stateId: "AD" },
  { lgId: "AD19", name: "Toungo", stateId: "AD" },
  { lgId: "AD2", name: "Fufore", stateId: "AD" },
  { lgId: "AD20", name: "Yola North", stateId: "AD" },
  { lgId: "AD21", name: "Yola South", stateId: "AD" },
  { lgId: "AD3", name: "Ganye", stateId: "AD" },
  { lgId: "AD4", name: "Girei", stateId: "AD" },
  { lgId: "AD5", name: "Gombi", stateId: "AD" },
  { lgId: "AD6", name: "Guyuk", stateId: "AD" },
  { lgId: "AD7", name: "Hong", stateId: "AD" },
  { lgId: "AD8", name: "Jada", stateId: "AD" },
  { lgId: "AD9", name: "Lamurde", stateId: "AD" },
  { lgId: "AK1", name: "Abak", stateId: "AK" },
  { lgId: "AK10", name: "Ibiono Ibom", stateId: "AK" },
  { lgId: "AK11", name: "Ika", stateId: "AK" },
  { lgId: "AK12", name: "Ikono", stateId: "AK" },
  { lgId: "AK13", name: "Ikot Abasi", stateId: "AK" },
  { lgId: "AK14", name: "Ikot Ekpene", stateId: "AK" },
  { lgId: "AK15", name: "Ini", stateId: "AK" },
  { lgId: "AK16", name: "Itu", stateId: "AK" },
  { lgId: "AK17", name: "Mbo", stateId: "AK" },
  { lgId: "AK18", name: "Mkpat Enin", stateId: "AK" },
  { lgId: "AK19", name: "Nsit Atai", stateId: "AK" },
  { lgId: "AK2", name: "Eastern Obolo", stateId: "AK" },
  { lgId: "AK20", name: "Nsit Ibom", stateId: "AK" },
  { lgId: "AK21", name: "Nsit Ubium", stateId: "AK" },
  { lgId: "AK22", name: "Obot Akara", stateId: "AK" },
  { lgId: "AK23", name: "Okobo", stateId: "AK" },
  { lgId: "AK24", name: "Onna", stateId: "AK" },
  { lgId: "AK25", name: "Oron", stateId: "AK" },
  { lgId: "AK26", name: "Oruk Anam", stateId: "AK" },
  { lgId: "AK27", name: "Udung Uko", stateId: "AK" },
  { lgId: "AK28", name: "Ukanafun", stateId: "AK" },
  { lgId: "AK29", name: "Uruan", stateId: "AK" },
  { lgId: "AK3", name: "Eket", stateId: "AK" },
  { lgId: "AK30", name: "Urue-Offong/Oruko", stateId: "AK" },
  { lgId: "AK31", name: "Uyo", stateId: "AK" },
  { lgId: "AK4", name: "Esit Eket", stateId: "AK" },
  { lgId: "AK5", name: "Essien Udim", stateId: "AK" },
  { lgId: "AK6", name: "Etim Ekpo", stateId: "AK" },
  { lgId: "AK7", name: "Etinan", stateId: "AK" },
  { lgId: "AK8", name: "Ibeno", stateId: "AK" },
  { lgId: "AK9", name: "Ibesikpo Asutan", stateId: "AK" },
  { lgId: "AN1", name: "Aguata", stateId: "AN" },
  { lgId: "AN10", name: "Idemili North", stateId: "AN" },
  { lgId: "AN11", name: "Idemili South", stateId: "AN" },
  { lgId: "AN12", name: "Ihiala", stateId: "AN" },
  { lgId: "AN13", name: "Njikoka", stateId: "AN" },
  { lgId: "AN14", name: "Nnewi North", stateId: "AN" },
  { lgId: "AN15", name: "Nnewi South", stateId: "AN" },
  { lgId: "AN16", name: "Ogbaru", stateId: "AN" },
  { lgId: "AN17", name: "Onitsha North", stateId: "AN" },
  { lgId: "AN18", name: "Onitsha South", stateId: "AN" },
  { lgId: "AN19", name: "Orumba North", stateId: "AN" },
  { lgId: "AN2", name: "Anambra East", stateId: "AN" },
  { lgId: "AN20", name: "Orumba South", stateId: "AN" },
  { lgId: "AN21", name: "Oyi", stateId: "AN" },
  { lgId: "AN3", name: "Anambra West", stateId: "AN" },
  { lgId: "AN4", name: "Anaocha", stateId: "AN" },
  { lgId: "AN5", name: "Awka North", stateId: "AN" },
  { lgId: "AN6", name: "Awka South", stateId: "AN" },
  { lgId: "AN7", name: "Ayamelum", stateId: "AN" },
  { lgId: "AN8", name: "Dunukofia", stateId: "AN" },
  { lgId: "AN9", name: "Ekwusigo", stateId: "AN" },
  { lgId: "BC1", name: "Alkaleri", stateId: "BC" },
  { lgId: "BC10", name: "Itas/Gadau", stateId: "BC" },
  { lgId: "BC11", name: "Jama'are", stateId: "BC" },
  { lgId: "BC12", name: "Katagum", stateId: "BC" },
  { lgId: "BC13", name: "Kirfi", stateId: "BC" },
  { lgId: "BC14", name: "Misau", stateId: "BC" },
  { lgId: "BC15", name: "Ningi", stateId: "BC" },
  { lgId: "BC16", name: "Shira", stateId: "BC" },
  { lgId: "BC17", name: "Tafawa-Balewa", stateId: "BC" },
  { lgId: "BC18", name: "Toro", stateId: "BC" },
  { lgId: "BC19", name: "Warji", stateId: "BC" },
  { lgId: "BC2", name: "Bauchi", stateId: "BC" },
  { lgId: "BC20", name: "Zaki", stateId: "BC" },
  { lgId: "BC3", name: "Bogoro", stateId: "BC" },
  { lgId: "BC4", name: "Damban", stateId: "BC" },
  { lgId: "BC5", name: "Darazo", stateId: "BC" },
  { lgId: "BC6", name: "Dass", stateId: "BC" },
  { lgId: "BC7", name: "Gamawa", stateId: "BC" },
  { lgId: "BC8", name: "Ganjuwa", stateId: "BC" },
  { lgId: "BC9", name: "Giade", stateId: "BC" },
  { lgId: "BN1", name: "Abadam", stateId: "BN" },
  { lgId: "BN10", name: "Guzamala", stateId: "BN" },
  { lgId: "BN11", name: "Gwoza", stateId: "BN" },
  { lgId: "BN12", name: "Hawul", stateId: "BN" },
  { lgId: "BN13", name: "Jere", stateId: "BN" },
  { lgId: "BN14", name: "Kaga", stateId: "BN" },
  { lgId: "BN15", name: "Kala/Balge", stateId: "BN" },
  { lgId: "BN16", name: "Konduga", stateId: "BN" },
  { lgId: "BN17", name: "Kukawa", stateId: "BN" },
  { lgId: "BN18", name: "Kwaya Kusar", stateId: "BN" },
  { lgId: "BN19", name: "Mafa", stateId: "BN" },
  { lgId: "BN2", name: "Askira/Uba", stateId: "BN" },
  { lgId: "BN20", name: "Magumeri", stateId: "BN" },
  { lgId: "BN21", name: "Maiduguri", stateId: "BN" },
  { lgId: "BN22", name: "Marte", stateId: "BN" },
  { lgId: "BN23", name: "Mobbar", stateId: "BN" },
  { lgId: "BN24", name: "Monguno", stateId: "BN" },
  { lgId: "BN25", name: "Ngala", stateId: "BN" },
  { lgId: "BN26", name: "Nganzai", stateId: "BN" },
  { lgId: "BN27", name: "Shani", stateId: "BN" },
  { lgId: "BN3", name: "Bama", stateId: "BN" },
  { lgId: "BN4", name: "Bayo", stateId: "BN" },
  { lgId: "BN5", name: "Biu", stateId: "BN" },
  { lgId: "BN6", name: "Chibok", stateId: "BN" },
  { lgId: "BN7", name: "Damboa", stateId: "BN" },
  { lgId: "BN8", name: "Dikwa", stateId: "BN" },
  { lgId: "BN9", name: "Gubio", stateId: "BN" },
  { lgId: "BU1", name: "Ado", stateId: "BU" },
  { lgId: "BU10", name: "Konshisha", stateId: "BU" },
  { lgId: "BU11", name: "Kwande", stateId: "BU" },
  { lgId: "BU12", name: "Logo", stateId: "BU" },
  { lgId: "BU13", name: "Makurdi", stateId: "BU" },
  { lgId: "BU14", name: "Obi Benue", stateId: "BU" },
  { lgId: "BU15", name: "Ogbadibo", stateId: "BU" },
  { lgId: "BU16", name: "Ohimini", stateId: "BU" },
  { lgId: "BU17", name: "Oju", stateId: "BU" },
  { lgId: "BU18", name: "Okpokwu", stateId: "BU" },
  { lgId: "BU19", name: "Oturkpo", stateId: "BU" },
  { lgId: "BU2", name: "Agatu", stateId: "BU" },
  { lgId: "BU20", name: "Tarka", stateId: "BU" },
  { lgId: "BU21", name: "Ukum", stateId: "BU" },
  { lgId: "BU22", name: "Ushongo", stateId: "BU" },
  { lgId: "BU23", name: "Vandeikya", stateId: "BU" },
  { lgId: "BU3", name: "Apa", stateId: "BU" },
  { lgId: "BU4", name: "Buruku", stateId: "BU" },
  { lgId: "BU5", name: "Gboko", stateId: "BU" },
  { lgId: "BU6", name: "Guma", stateId: "BU" },
  { lgId: "BU7", name: "Gwer East", stateId: "BU" },
  { lgId: "BU8", name: "Gwer West", stateId: "BU" },
  { lgId: "BU9", name: "Katsina-Ala", stateId: "BU" },
  { lgId: "BY1", name: "Brass", stateId: "BY" },
  { lgId: "BY2", name: "Ekeremor", stateId: "BY" },
  { lgId: "BY3", name: "Kolokuma/Opokuma", stateId: "BY" },
  { lgId: "BY4", name: "Nembe", stateId: "BY" },
  { lgId: "BY5", name: "Ogbia", stateId: "BY" },
  { lgId: "BY6", name: "Sagbama", stateId: "BY" },
  { lgId: "BY7", name: "Southern Ijaw", stateId: "BY" },
  { lgId: "BY8", name: "Yenagoa", stateId: "BY" },
  { lgId: "CR1", name: "Abi", stateId: "CR" },
  { lgId: "CR10", name: "Etung", stateId: "CR" },
  { lgId: "CR11", name: "Ikom", stateId: "CR" },
  { lgId: "CR12", name: "Obanliku", stateId: "CR" },
  { lgId: "CR13", name: "Obubra", stateId: "CR" },
  { lgId: "CR14", name: "Obudu", stateId: "CR" },
  { lgId: "CR15", name: "Odukpani", stateId: "CR" },
  { lgId: "CR16", name: "Ogoja", stateId: "CR" },
  { lgId: "CR17", name: "Yakurr", stateId: "CR" },
  { lgId: "CR18", name: "Yala", stateId: "CR" },
  { lgId: "CR2", name: "Akamkpa", stateId: "CR" },
  { lgId: "CR3", name: "Akpabuyo", stateId: "CR" },
  { lgId: "CR4", name: "Bakassi", stateId: "CR" },
  { lgId: "CR5", name: "Bekwara", stateId: "CR" },
  { lgId: "CR6", name: "Biase", stateId: "CR" },
  { lgId: "CR7", name: "Boki", stateId: "CR" },
  { lgId: "CR8", name: "Calabar Municipal", stateId: "CR" },
  { lgId: "CR9", name: "Calabar South", stateId: "CR" },
  { lgId: "DT1", name: "Aniocha North", stateId: "DT" },
  { lgId: "DT10", name: "Isoko South", stateId: "DT" },
  { lgId: "DT11", name: "Ndokwa East", stateId: "DT" },
  { lgId: "DT12", name: "Ndokwa West", stateId: "DT" },
  { lgId: "DT13", name: "Okpe", stateId: "DT" },
  { lgId: "DT14", name: "Oshimili North", stateId: "DT" },
  { lgId: "DT15", name: "Oshimili South", stateId: "DT" },
  { lgId: "DT16", name: "Patani", stateId: "DT" },
  { lgId: "DT17", name: "Sapele", stateId: "DT" },
  { lgId: "DT18", name: "Udu", stateId: "DT" },
  { lgId: "DT19", name: "Ughelli North", stateId: "DT" },
  { lgId: "DT2", name: "Aniocha South", stateId: "DT" },
  { lgId: "DT20", name: "Ughelli South", stateId: "DT" },
  { lgId: "DT21", name: "Ukwuani", stateId: "DT" },
  { lgId: "DT22", name: "Uvwie", stateId: "DT" },
  { lgId: "DT23", name: "Warri North", stateId: "DT" },
  { lgId: "DT24", name: "Warri South", stateId: "DT" },
  { lgId: "DT25", name: "Warri South West", stateId: "DT" },
  { lgId: "DT3", name: "Bomadi", stateId: "DT" },
  { lgId: "DT4", name: "Burutu", stateId: "DT" },
  { lgId: "DT5", name: "Ethiope East", stateId: "DT" },
  { lgId: "DT6", name: "Ethiope West", stateId: "DT" },
  { lgId: "DT7", name: "Ika North East", stateId: "DT" },
  { lgId: "DT8", name: "Ika South", stateId: "DT" },
  { lgId: "DT9", name: "Isoko North", stateId: "DT" },
  { lgId: "ED1", name: "Akoko-Edo", stateId: "ED" },
  { lgId: "ED10", name: "Igueben", stateId: "ED" },
  { lgId: "ED11", name: "Ikpoba-Okha", stateId: "ED" },
  { lgId: "ED12", name: "Oredo", stateId: "ED" },
  { lgId: "ED13", name: "Orhionmwon", stateId: "ED" },
  { lgId: "ED14", name: "Ovia North East", stateId: "ED" },
  { lgId: "ED15", name: "Ovia South West", stateId: "ED" },
  { lgId: "ED16", name: "Owan East", stateId: "ED" },
  { lgId: "ED17", name: "Owan West", stateId: "ED" },
  { lgId: "ED18", name: "Uhunmwonde", stateId: "ED" },
  { lgId: "ED2", name: "Egor", stateId: "ED" },
  { lgId: "ED3", name: "Esan Central", stateId: "ED" },
  { lgId: "ED4", name: "Esan North East", stateId: "ED" },
  { lgId: "ED5", name: "Esan South East", stateId: "ED" },
  { lgId: "ED6", name: "Esan West", stateId: "ED" },
  { lgId: "ED7", name: "Etsako Central", stateId: "ED" },
  { lgId: "ED8", name: "Etsako East", stateId: "ED" },
  { lgId: "ED9", name: "Etsako West", stateId: "ED" },
  { lgId: "EK1", name: "Ado Ekiti", stateId: "EK" },
  { lgId: "EK10", name: "Ikere", stateId: "EK" },
  { lgId: "EK11", name: "Ikole", stateId: "EK" },
  { lgId: "EK12", name: "Ilejemeje", stateId: "EK" },
  { lgId: "EK13", name: "Irepodun/Ifelodun", stateId: "EK" },
  { lgId: "EK14", name: "Ise/Orun", stateId: "EK" },
  { lgId: "EK15", name: "Moba", stateId: "EK" },
  { lgId: "EK16", name: "Oye", stateId: "EK" },
  { lgId: "EK2", name: "Aiyekire (Gbonyin)", stateId: "EK" },
  { lgId: "EK3", name: "Efon", stateId: "EK" },
  { lgId: "EK4", name: "Ekiti East", stateId: "EK" },
  { lgId: "EK5", name: "Ekiti South West", stateId: "EK" },
  { lgId: "EK6", name: "Ekiti West", stateId: "EK" },
  { lgId: "EK7", name: "Emure", stateId: "EK" },
  { lgId: "EK8", name: "Ido-Osi", stateId: "EK" },
  { lgId: "EK9", name: "Ijero", stateId: "EK" },
  { lgId: "EN1", name: "Aninri", stateId: "EN" },
  { lgId: "EN10", name: "Isi-Uzo", stateId: "EN" },
  { lgId: "EN11", name: "Nkanu East", stateId: "EN" },
  { lgId: "EN12", name: "Nkanu West", stateId: "EN" },
  { lgId: "EN13", name: "Nsukka", stateId: "EN" },
  { lgId: "EN14", name: "Oji-River", stateId: "EN" },
  { lgId: "EN15", name: "Udenu", stateId: "EN" },
  { lgId: "EN16", name: "Udi", stateId: "EN" },
  { lgId: "EN17", name: "Uzo-Uwani", stateId: "EN" },
  { lgId: "EN2", name: "Awgu", stateId: "EN" },
  { lgId: "EN3", name: "Enugu East", stateId: "EN" },
  { lgId: "EN4", name: "Enugu North", stateId: "EN" },
  { lgId: "EN5", name: "Enugu South", stateId: "EN" },
  { lgId: "EN6", name: "Ezeagu", stateId: "EN" },
  { lgId: "EN7", name: "Igbo-Etiti", stateId: "EN" },
  { lgId: "EN8", name: "Igbo-Eze North", stateId: "EN" },
  { lgId: "EN9", name: "Igbo-Eze South", stateId: "EN" },
  { lgId: "EY1", name: "Abakaliki", stateId: "EY" },
  { lgId: "EY10", name: "Izzi", stateId: "EY" },
  { lgId: "EY11", name: "Ohaozara", stateId: "EY" },
  { lgId: "EY12", name: "Ohaukwu", stateId: "EY" },
  { lgId: "EY13", name: "Onicha", stateId: "EY" },
  { lgId: "EY2", name: "Afikpo North", stateId: "EY" },
  { lgId: "EY3", name: "Afikpo South", stateId: "EY" },
  { lgId: "EY4", name: "Ebonyi", stateId: "EY" },
  { lgId: "EY5", name: "Ezza North", stateId: "EY" },
  { lgId: "EY6", name: "Ezza South", stateId: "EY" },
  { lgId: "EY7", name: "Ikwo", stateId: "EY" },
  { lgId: "EY8", name: "Ishielu", stateId: "EY" },
  { lgId: "EY9", name: "Ivo", stateId: "EY" },
  { lgId: "FC1", name: "Abaji", stateId: "FCT" },
  { lgId: "FC2", name: "Abuja Municipal Area Council", stateId: "FCT" },
  { lgId: "FC3", name: "Bwari", stateId: "FCT" },
  { lgId: "FC4", name: "Gwagwalada", stateId: "FCT" },
  { lgId: "FC5", name: "Kuje", stateId: "FCT" },
  { lgId: "FC6", name: "Kwali", stateId: "FCT" },
  { lgId: "GM1", name: "Akko", stateId: "GM" },
  { lgId: "GM10", name: "Shomgom", stateId: "GM" },
  { lgId: "GM11", name: "Yamaltu/Deba", stateId: "GM" },
  { lgId: "GM2", name: "Balanga", stateId: "GM" },
  { lgId: "GM3", name: "Billiri", stateId: "GM" },
  { lgId: "GM4", name: "Dukku", stateId: "GM" },
  { lgId: "GM5", name: "Funakaye", stateId: "GM" },
  { lgId: "GM6", name: "Gombe", stateId: "GM" },
  { lgId: "GM7", name: "Kaltungo", stateId: "GM" },
  { lgId: "GM8", name: "Kwami", stateId: "GM" },
  { lgId: "GM9", name: "Nafada", stateId: "GM" },
  { lgId: "IM1", name: "Abo-Mbaise", stateId: "IM" },
  { lgId: "IM10", name: "Isu", stateId: "IM" },
  { lgId: "IM11", name: "Mbaitoli", stateId: "IM" },
  { lgId: "IM12", name: "Ngor-Okpala", stateId: "IM" },
  { lgId: "IM13", name: "Njaba", stateId: "IM" },
  { lgId: "IM14", name: "Nkwerre", stateId: "IM" },
  { lgId: "IM15", name: "Nwangele", stateId: "IM" },
  { lgId: "IM16", name: "Obowo", stateId: "IM" },
  { lgId: "IM17", name: "Oguta", stateId: "IM" },
  { lgId: "IM18", name: "Ohaji/Egbema", stateId: "IM" },
  { lgId: "IM19", name: "Okigwe", stateId: "IM" },
  { lgId: "IM2", name: "Ahiazu-Mbaise", stateId: "IM" },
  { lgId: "IM20", name: "Orlu", stateId: "IM" },
  { lgId: "IM21", name: "Orsu", stateId: "IM" },
  { lgId: "IM22", name: "Oru East", stateId: "IM" },
  { lgId: "IM23", name: "Oru West", stateId: "IM" },
  { lgId: "IM24", name: "Owerri Municipal", stateId: "IM" },
  { lgId: "IM25", name: "Owerri North", stateId: "IM" },
  { lgId: "IM26", name: "Owerri West", stateId: "IM" },
  { lgId: "IM27", name: "Unuimo", stateId: "IM" },
  { lgId: "IM3", name: "Ehime-Mbano", stateId: "IM" },
  { lgId: "IM4", name: "Ezinihitte", stateId: "IM" },
  { lgId: "IM5", name: "Ideato North", stateId: "IM" },
  { lgId: "IM6", name: "Ideato South", stateId: "IM" },
  { lgId: "IM7", name: "Ihitte/Uboma", stateId: "IM" },
  { lgId: "IM8", name: "Ikeduru", stateId: "IM" },
  { lgId: "IM9", name: "Isiala-Mbano", stateId: "IM" },
  { lgId: "JG1", name: "Auyo", stateId: "JG" },
  { lgId: "JG10", name: "Guri", stateId: "JG" },
  { lgId: "JG11", name: "Gwaram", stateId: "JG" },
  { lgId: "JG12", name: "Gwiwa", stateId: "JG" },
  { lgId: "JG13", name: "Hadejia", stateId: "JG" },
  { lgId: "JG14", name: "Jahun", stateId: "JG" },
  { lgId: "JG15", name: "Kafin Hausa", stateId: "JG" },
  { lgId: "JG16", name: "Kaugama", stateId: "JG" },
  { lgId: "JG17", name: "Kazaure", stateId: "JG" },
  { lgId: "JG18", name: "Kiri Kasama", stateId: "JG" },
  { lgId: "JG19", name: "Kiyawa", stateId: "JG" },
  { lgId: "JG2", name: "Babura", stateId: "JG" },
  { lgId: "JG20", name: "Maigatari", stateId: "JG" },
  { lgId: "JG21", name: "Malam Madori", stateId: "JG" },
  { lgId: "JG22", name: "Miga", stateId: "JG" },
  { lgId: "JG23", name: "Ringim", stateId: "JG" },
  { lgId: "JG24", name: "Roni", stateId: "JG" },
  { lgId: "JG25", name: "Sule Tankarkar", stateId: "JG" },
  { lgId: "JG26", name: "Taura", stateId: "JG" },
  { lgId: "JG27", name: "Yankwashi", stateId: "JG" },
  { lgId: "JG3", name: "Biriniwa", stateId: "JG" },
  { lgId: "JG4", name: "Birnin Kudu", stateId: "JG" },
  { lgId: "JG5", name: "Buji", stateId: "JG" },
  { lgId: "JG6", name: "Dutse", stateId: "JG" },
  { lgId: "JG7", name: "Gagarawa", stateId: "JG" },
  { lgId: "JG8", name: "Garki", stateId: "JG" },
  { lgId: "JG9", name: "Gumel", stateId: "JG" },
  { lgId: "KB1", name: "Aleiro", stateId: "KB" },
  { lgId: "KB10", name: "Gwandu", stateId: "KB" },
  { lgId: "KB11", name: "Jega", stateId: "KB" },
  { lgId: "KB12", name: "Kalgo", stateId: "KB" },
  { lgId: "KB13", name: "Koko/Besse", stateId: "KB" },
  { lgId: "KB14", name: "Maiyama", stateId: "KB" },
  { lgId: "KB15", name: "Ngaski", stateId: "KB" },
  { lgId: "KB16", name: "Sakaba", stateId: "KB" },
  { lgId: "KB17", name: "Shanga", stateId: "KB" },
  { lgId: "KB18", name: "Suru", stateId: "KB" },
  { lgId: "KB19", name: "Wasagu/Danko", stateId: "KB" },
  { lgId: "KB2", name: "Arewa-Dandi", stateId: "KB" },
  { lgId: "KB20", name: "Yauri", stateId: "KB" },
  { lgId: "KB21", name: "Zuru", stateId: "KB" },
  { lgId: "KB3", name: "Argungu", stateId: "KB" },
  { lgId: "KB4", name: "Augie", stateId: "KB" },
  { lgId: "KB5", name: "Bagudo", stateId: "KB" },
  { lgId: "KB6", name: "Birnin Kebbi", stateId: "KB" },
  { lgId: "KB7", name: "Bunza", stateId: "KB" },
  { lgId: "KB8", name: "Dandi", stateId: "KB" },
  { lgId: "KB9", name: "Fakai", stateId: "KB" },
  { lgId: "KD1", name: "Birnin-Gwari", stateId: "KD" },
  { lgId: "KD10", name: "Kaduna South", stateId: "KD" },
  { lgId: "KD11", name: "Kagarko", stateId: "KD" },
  { lgId: "KD12", name: "Kajuru", stateId: "KD" },
  { lgId: "KD13", name: "Kaura", stateId: "KD" },
  { lgId: "KD14", name: "Kauru", stateId: "KD" },
  { lgId: "KD15", name: "Kubau", stateId: "KD" },
  { lgId: "KD16", name: "Kudan", stateId: "KD" },
  { lgId: "KD17", name: "Lere", stateId: "KD" },
  { lgId: "KD18", name: "Makarfi", stateId: "KD" },
  { lgId: "KD19", name: "Sabon-Gari", stateId: "KD" },
  { lgId: "KD2", name: "Chikun", stateId: "KD" },
  { lgId: "KD20", name: "Sanga", stateId: "KD" },
  { lgId: "KD21", name: "Soba", stateId: "KD" },
  { lgId: "KD22", name: "Zangon-Kataf", stateId: "KD" },
  { lgId: "KD23", name: "Zaria", stateId: "KD" },
  { lgId: "KD3", name: "Giwa", stateId: "KD" },
  { lgId: "KD4", name: "Igabi", stateId: "KD" },
  { lgId: "KD5", name: "Ikara", stateId: "KD" },
  { lgId: "KD6", name: "Jaba", stateId: "KD" },
  { lgId: "KD7", name: "Jema'a", stateId: "KD" },
  { lgId: "KD8", name: "Kachia", stateId: "KD" },
  { lgId: "KD9", name: "Kaduna North", stateId: "KD" },
  { lgId: "KG1", name: "Adavi", stateId: "KG" },
  { lgId: "KG10", name: "Kabba/Bunu", stateId: "KG" },
  { lgId: "KG11", name: "Kogi", stateId: "KG" },
  { lgId: "KG12", name: "Lokoja", stateId: "KG" },
  { lgId: "KG13", name: "Mopa-Muro", stateId: "KG" },
  { lgId: "KG14", name: "Ofu", stateId: "KG" },
  { lgId: "KG15", name: "Ogori/Magongo", stateId: "KG" },
  { lgId: "KG16", name: "Okehi", stateId: "KG" },
  { lgId: "KG17", name: "Okene", stateId: "KG" },
  { lgId: "KG18", name: "Olamaboro", stateId: "KG" },
  { lgId: "KG19", name: "Omala", stateId: "KG" },
  { lgId: "KG2", name: "Ajaokuta", stateId: "KG" },
  { lgId: "KG20", name: "Yagba East", stateId: "KG" },
  { lgId: "KG21", name: "Yagba West", stateId: "KG" },
  { lgId: "KG3", name: "Ankpa", stateId: "KG" },
  { lgId: "KG4", name: "Bassa Kogi", stateId: "KG" },
  { lgId: "KG5", name: "Dekina", stateId: "KG" },
  { lgId: "KG6", name: "Ibaji", stateId: "KG" },
  { lgId: "KG7", name: "Idah", stateId: "KG" },
  { lgId: "KG8", name: "Igalamela-Odolu", stateId: "KG" },
  { lgId: "KG9", name: "Ijumu", stateId: "KG" },
  { lgId: "KN1", name: "Ajingi", stateId: "KN" },
  { lgId: "KN10", name: "Dawakin Tofa", stateId: "KN" },
  { lgId: "KN11", name: "Doguwa", stateId: "KN" },
  { lgId: "KN12", name: "Fagge", stateId: "KN" },
  { lgId: "KN13", name: "Gabasawa", stateId: "KN" },
  { lgId: "KN14", name: "Garko", stateId: "KN" },
  { lgId: "KN15", name: "Garum Mallam", stateId: "KN" },
  { lgId: "KN16", name: "Gaya", stateId: "KN" },
  { lgId: "KN17", name: "Gezawa", stateId: "KN" },
  { lgId: "KN18", name: "Gwale", stateId: "KN" },
  { lgId: "KN19", name: "Gwarzo", stateId: "KN" },
  { lgId: "KN2", name: "Albasu", stateId: "KN" },
  { lgId: "KN20", name: "Kabo", stateId: "KN" },
  { lgId: "KN21", name: "Kano Municipal", stateId: "KN" },
  { lgId: "KN22", name: "Karaye", stateId: "KN" },
  { lgId: "KN23", name: "Kibiya", stateId: "KN" },
  { lgId: "KN24", name: "Kiru", stateId: "KN" },
  { lgId: "KN25", name: "Kumbotso", stateId: "KN" },
  { lgId: "KN26", name: "Kunchi", stateId: "KN" },
  { lgId: "KN27", name: "Kura", stateId: "KN" },
  { lgId: "KN28", name: "Madobi", stateId: "KN" },
  { lgId: "KN29", name: "Makoda", stateId: "KN" },
  { lgId: "KN3", name: "Bagwai", stateId: "KN" },
  { lgId: "KN30", name: "Minjibir", stateId: "KN" },
  { lgId: "KN31", name: "Nasarawa Kano", stateId: "KN" },
  { lgId: "KN32", name: "Rano", stateId: "KN" },
  { lgId: "KN33", name: "Rimin Gado", stateId: "KN" },
  { lgId: "KN34", name: "Rogo", stateId: "KN" },
  { lgId: "KN35", name: "Shanono", stateId: "KN" },
  { lgId: "KN36", name: "Sumaila", stateId: "KN" },
  { lgId: "KN37", name: "Takai", stateId: "KN" },
  { lgId: "KN38", name: "Tarauni", stateId: "KN" },
  { lgId: "KN39", name: "Tofa", stateId: "KN" },
  { lgId: "KN4", name: "Bebeji", stateId: "KN" },
  { lgId: "KN40", name: "Tsanyawa", stateId: "KN" },
  { lgId: "KN41", name: "Tudun Wada", stateId: "KN" },
  { lgId: "KN42", name: "Ungogo", stateId: "KN" },
  { lgId: "KN43", name: "Warawa", stateId: "KN" },
  { lgId: "KN44", name: "Wudil", stateId: "KN" },
  { lgId: "KN5", name: "Bichi", stateId: "KN" },
  { lgId: "KN6", name: "Bunkure", stateId: "KN" },
  { lgId: "KN7", name: "Dala", stateId: "KN" },
  { lgId: "KN8", name: "Dambatta", stateId: "KN" },
  { lgId: "KN9", name: "Dawakin Kudu", stateId: "KN" },
  { lgId: "KT1", name: "Bakori", stateId: "KT" },
  { lgId: "KT10", name: "Daura", stateId: "KT" },
  { lgId: "KT11", name: "Dutsi", stateId: "KT" },
  { lgId: "KT12", name: "Dutsin-Ma", stateId: "KT" },
  { lgId: "KT13", name: "Faskari", stateId: "KT" },
  { lgId: "KT14", name: "Funtua", stateId: "KT" },
  { lgId: "KT15", name: "Ingawa", stateId: "KT" },
  { lgId: "KT16", name: "Jibia", stateId: "KT" },
  { lgId: "KT17", name: "Kafur", stateId: "KT" },
  { lgId: "KT18", name: "Kaita", stateId: "KT" },
  { lgId: "KT19", name: "Kankara", stateId: "KT" },
  { lgId: "KT2", name: "Batagarawa", stateId: "KT" },
  { lgId: "KT20", name: "Kankia", stateId: "KT" },
  { lgId: "KT21", name: "Katsina", stateId: "KT" },
  { lgId: "KT22", name: "Kurfi", stateId: "KT" },
  { lgId: "KT23", name: "Kusada", stateId: "KT" },
  { lgId: "KT24", name: "Mai'adua", stateId: "KT" },
  { lgId: "KT25", name: "Malumfashi", stateId: "KT" },
  { lgId: "KT26", name: "Mani", stateId: "KT" },
  { lgId: "KT27", name: "Mashi", stateId: "KT" },
  { lgId: "KT28", name: "Matazu", stateId: "KT" },
  { lgId: "KT29", name: "Musawa", stateId: "KT" },
  { lgId: "KT3", name: "Batsari", stateId: "KT" },
  { lgId: "KT30", name: "Rimi", stateId: "KT" },
  { lgId: "KT31", name: "Sabuwa", stateId: "KT" },
  { lgId: "KT32", name: "Safana", stateId: "KT" },
  { lgId: "KT33", name: "Sandamu", stateId: "KT" },
  { lgId: "KT34", name: "Zango", stateId: "KT" },
  { lgId: "KT4", name: "Baure", stateId: "KT" },
  { lgId: "KT5", name: "Bindawa", stateId: "KT" },
  { lgId: "KT6", name: "Charanchi", stateId: "KT" },
  { lgId: "KT7", name: "Dandume", stateId: "KT" },
  { lgId: "KT8", name: "Danja", stateId: "KT" },
  { lgId: "KT9", name: "Dan Musa", stateId: "KT" },
  { lgId: "KW1", name: "Asa", stateId: "KW" },
  { lgId: "KW10", name: "Isin", stateId: "KW" },
  { lgId: "KW11", name: "Kaiama", stateId: "KW" },
  { lgId: "KW12", name: "Moro", stateId: "KW" },
  { lgId: "KW13", name: "Offa", stateId: "KW" },
  { lgId: "KW14", name: "Oke-Ero", stateId: "KW" },
  { lgId: "KW15", name: "Oyun", stateId: "KW" },
  { lgId: "KW16", name: "Pategi", stateId: "KW" },
  { lgId: "KW2", name: "Baruten", stateId: "KW" },
  { lgId: "KW3", name: "Edu", stateId: "KW" },
  { lgId: "KW4", name: "Ekiti", stateId: "KW" },
  { lgId: "KW5", name: "Ifelodun Kwara", stateId: "KW" },
  { lgId: "KW6", name: "Ilorin East", stateId: "KW" },
  { lgId: "KW7", name: "Ilorin South", stateId: "KW" },
  { lgId: "KW8", name: "Ilorin West", stateId: "KW" },
  { lgId: "KW9", name: "Irepodun Kwara", stateId: "KW" },
  { lgId: "LG1", name: "Agege", stateId: "LG" },
  { lgId: "LG10", name: "Ifako-Ijaye", stateId: "LG" },
  { lgId: "LG11", name: "Ikeja", stateId: "LG" },
  { lgId: "LG12", name: "Ikorodu", stateId: "LG" },
  { lgId: "LG13", name: "Kosofe", stateId: "LG" },
  { lgId: "LG14", name: "Lagos Island", stateId: "LG" },
  { lgId: "LG15", name: "Lagos Mainland", stateId: "LG" },
  { lgId: "LG16", name: "Mushin", stateId: "LG" },
  { lgId: "LG17", name: "Ojo", stateId: "LG" },
  { lgId: "LG18", name: "Oshodi-Isolo", stateId: "LG" },
  { lgId: "LG19", name: "Shomolu", stateId: "LG" },
  { lgId: "LG2", name: "Ajeromi-Ifelodun", stateId: "LG" },
  { lgId: "LG20", name: "Surulere Lagos", stateId: "LG" },
  { lgId: "LG3", name: "Alimosho", stateId: "LG" },
  { lgId: "LG4", name: "Amuwo-Odofin", stateId: "LG" },
  { lgId: "LG5", name: "Apapa", stateId: "LG" },
  { lgId: "LG6", name: "Badagry", stateId: "LG" },
  { lgId: "LG7", name: "Epe", stateId: "LG" },
  { lgId: "LG8", name: "Eti-Osa", stateId: "LG" },
  { lgId: "LG9", name: "Ibeju/Lekki", stateId: "LG" },
  { lgId: "NG1", name: "Agaie", stateId: "NG" },
  { lgId: "NG10", name: "Katcha", stateId: "NG" },
  { lgId: "NG11", name: "Kontagora", stateId: "NG" },
  { lgId: "NG12", name: "Lapai", stateId: "NG" },
  { lgId: "NG13", name: "Lavun", stateId: "NG" },
  { lgId: "NG14", name: "Magama", stateId: "NG" },
  { lgId: "NG15", name: "Mariga", stateId: "NG" },
  { lgId: "NG16", name: "Mashegu", stateId: "NG" },
  { lgId: "NG17", name: "Mokwa", stateId: "NG" },
  { lgId: "NG18", name: "Muya", stateId: "NG" },
  { lgId: "NG19", name: "Paikoro", stateId: "NG" },
  { lgId: "NG2", name: "Agwara", stateId: "NG" },
  { lgId: "NG20", name: "Rafi", stateId: "NG" },
  { lgId: "NG21", name: "Rijau", stateId: "NG" },
  { lgId: "NG22", name: "Shiroro", stateId: "NG" },
  { lgId: "NG23", name: "Suleja", stateId: "NG" },
  { lgId: "NG24", name: "Tafa", stateId: "NG" },
  { lgId: "NG25", name: "Wushishi", stateId: "NG" },
  { lgId: "NG3", name: "Bida", stateId: "NG" },
  { lgId: "NG4", name: "Borgu", stateId: "NG" },
  { lgId: "NG5", name: "Bosso", stateId: "NG" },
  { lgId: "NG6", name: "Chanchaga", stateId: "NG" },
  { lgId: "NG7", name: "Edati", stateId: "NG" },
  { lgId: "NG8", name: "Gbako", stateId: "NG" },
  { lgId: "NG9", name: "Gurara", stateId: "NG" },
  { lgId: "NS1", name: "Akwanga", stateId: "NS" },
  { lgId: "NS10", name: "Nasarawa-Eggon", stateId: "NS" },
  { lgId: "NS11", name: "Obi", stateId: "NS" },
  { lgId: "NS12", name: "Toto", stateId: "NS" },
  { lgId: "NS13", name: "Wamba", stateId: "NS" },
  { lgId: "NS2", name: "Awe", stateId: "NS" },
  { lgId: "NS3", name: "Doma", stateId: "NS" },
  { lgId: "NS4", name: "Karu", stateId: "NS" },
  { lgId: "NS5", name: "Keana", stateId: "NS" },
  { lgId: "NS6", name: "Keffi", stateId: "NS" },
  { lgId: "NS7", name: "Kokona", stateId: "NS" },
  { lgId: "NS8", name: "Lafia", stateId: "NS" },
  { lgId: "NS9", name: "Nasarawa", stateId: "NS" },
  { lgId: "OD1", name: "Akoko North East", stateId: "OD" },
  { lgId: "OD10", name: "Ilaje", stateId: "OD" },
  { lgId: "OD11", name: "Ile-Oluji-Okeigbo", stateId: "OD" },
  { lgId: "OD12", name: "Irele", stateId: "OD" },
  { lgId: "OD13", name: "Odigbo", stateId: "OD" },
  { lgId: "OD14", name: "Okitipupa", stateId: "OD" },
  { lgId: "OD15", name: "Ondo East", stateId: "OD" },
  { lgId: "OD16", name: "Ondo West", stateId: "OD" },
  { lgId: "OD17", name: "Ose", stateId: "OD" },
  { lgId: "OD18", name: "Owo", stateId: "OD" },
  { lgId: "OD2", name: "Akoko North West", stateId: "OD" },
  { lgId: "OD3", name: "Akoko South East", stateId: "OD" },
  { lgId: "OD4", name: "Akoko South West", stateId: "OD" },
  { lgId: "OD5", name: "Akure North", stateId: "OD" },
  { lgId: "OD6", name: "Akure South", stateId: "OD" },
  { lgId: "OD7", name: "Ese-Odo", stateId: "OD" },
  { lgId: "OD8", name: "Idanre", stateId: "OD" },
  { lgId: "OD9", name: "Ifedore", stateId: "OD" },
  { lgId: "OG1", name: "Abeokuta North", stateId: "OG" },
  { lgId: "OG10", name: "Ijebu North East", stateId: "OG" },
  { lgId: "OG11", name: "Ijebu Ode", stateId: "OG" },
  { lgId: "OG12", name: "Ikenne", stateId: "OG" },
  { lgId: "OG13", name: "Imeko Afon", stateId: "OG" },
  { lgId: "OG14", name: "Ipokia", stateId: "OG" },
  { lgId: "OG15", name: "Obafemi-Owode", stateId: "OG" },
  { lgId: "OG16", name: "Odeda", stateId: "OG" },
  { lgId: "OG17", name: "Odogbolu", stateId: "OG" },
  { lgId: "OG18", name: "Ogun Waterside", stateId: "OG" },
  { lgId: "OG19", name: "Remo North", stateId: "OG" },
  { lgId: "OG2", name: "Abeokuta South", stateId: "OG" },
  { lgId: "OG20", name: "Sagamu", stateId: "OG" },
  { lgId: "OG3", name: "Ado-Odo/Ota", stateId: "OG" },
  { lgId: "OG4", name: "Egbado North", stateId: "OG" },
  { lgId: "OG5", name: "Egbado South", stateId: "OG" },
  { lgId: "OG6", name: "Ewekoro", stateId: "OG" },
  { lgId: "OG7", name: "Ifo", stateId: "OG" },
  { lgId: "OG8", name: "Ijebu East", stateId: "OG" },
  { lgId: "OG9", name: "Ijebu North", stateId: "OG" },
  { lgId: "OS1", name: "Aiyedaade", stateId: "OS" },
  { lgId: "OS10", name: "Ejigbo", stateId: "OS" },
  { lgId: "OS11", name: "Ife Central", stateId: "OS" },
  { lgId: "OS12", name: "Ifedayo", stateId: "OS" },
  { lgId: "OS13", name: "Ife East", stateId: "OS" },
  { lgId: "OS14", name: "Ifelodun", stateId: "OS" },
  { lgId: "OS15", name: "Ife North", stateId: "OS" },
  { lgId: "OS16", name: "Ife South", stateId: "OS" },
  { lgId: "OS17", name: "Ila", stateId: "OS" },
  { lgId: "OS18", name: "Ilesha East", stateId: "OS" },
  { lgId: "OS19", name: "Ilesha West", stateId: "OS" },
  { lgId: "OS2", name: "Aiyedire", stateId: "OS" },
  { lgId: "OS20", name: "Irepodun", stateId: "OS" },
  { lgId: "OS21", name: "Irewole", stateId: "OS" },
  { lgId: "OS22", name: "Isokan", stateId: "OS" },
  { lgId: "OS23", name: "Iwo", stateId: "OS" },
  { lgId: "OS24", name: "Obokun", stateId: "OS" },
  { lgId: "OS25", name: "Odo-Otin", stateId: "OS" },
  { lgId: "OS26", name: "Ola-Oluwa", stateId: "OS" },
  { lgId: "OS27", name: "Olorunda", stateId: "OS" },
  { lgId: "OS28", name: "Oriade", stateId: "OS" },
  { lgId: "OS29", name: "Orolu", stateId: "OS" },
  { lgId: "OS3", name: "Atakunmosa East", stateId: "OS" },
  { lgId: "OS30", name: "Osogbo", stateId: "OS" },
  { lgId: "OS4", name: "Atakunmosa West", stateId: "OS" },
  { lgId: "OS5", name: "Boluwaduro", stateId: "OS" },
  { lgId: "OS6", name: "Boripe", stateId: "OS" },
  { lgId: "OS7", name: "Ede North", stateId: "OS" },
  { lgId: "OS8", name: "Ede South", stateId: "OS" },
  { lgId: "OS9", name: "Egbedore", stateId: "OS" },
  { lgId: "OY1", name: "Afijio", stateId: "OY" },
  { lgId: "OY10", name: "Ibadan South West", stateId: "OY" },
  { lgId: "OY11", name: "Ibarapa Central", stateId: "OY" },
  { lgId: "OY12", name: "Ibarapa East", stateId: "OY" },
  { lgId: "OY13", name: "Ibarapa North", stateId: "OY" },
  { lgId: "OY14", name: "Ido", stateId: "OY" },
  { lgId: "OY15", name: "Irepo", stateId: "OY" },
  { lgId: "OY16", name: "Iseyin", stateId: "OY" },
  { lgId: "OY17", name: "Itesiwaju", stateId: "OY" },
  { lgId: "OY18", name: "Iwajowa", stateId: "OY" },
  { lgId: "OY19", name: "Kajola", stateId: "OY" },
  { lgId: "OY2", name: "Akinyele", stateId: "OY" },
  { lgId: "OY20", name: "Lagelu", stateId: "OY" },
  { lgId: "OY21", name: "Ogbomosho North", stateId: "OY" },
  { lgId: "OY22", name: "Ogbomosho South", stateId: "OY" },
  { lgId: "OY23", name: "Ogo Oluwa", stateId: "OY" },
  { lgId: "OY24", name: "Olorunsogo", stateId: "OY" },
  { lgId: "OY25", name: "Oluyole", stateId: "OY" },
  { lgId: "OY26", name: "Ona-Ara", stateId: "OY" },
  { lgId: "OY27", name: "Orelope", stateId: "OY" },
  { lgId: "OY28", name: "Ori Ire", stateId: "OY" },
  { lgId: "OY29", name: "Oyo East", stateId: "OY" },
  { lgId: "OY3", name: "Atiba", stateId: "OY" },
  { lgId: "OY30", name: "Oyo West", stateId: "OY" },
  { lgId: "OY31", name: "Saki East", stateId: "OY" },
  { lgId: "OY32", name: "Saki West", stateId: "OY" },
  { lgId: "OY33", name: "Surulere", stateId: "OY" },
  { lgId: "OY4", name: "Atisbo", stateId: "OY" },
  { lgId: "OY5", name: "Egbeda", stateId: "OY" },
  { lgId: "OY6", name: "Ibadan North", stateId: "OY" },
  { lgId: "OY7", name: "Ibadan North East", stateId: "OY" },
  { lgId: "OY8", name: "Ibadan North West", stateId: "OY" },
  { lgId: "OY9", name: "Ibadan South East", stateId: "OY" },
  { lgId: "PL1", name: "Barkin Ladi", stateId: "PL" },
  { lgId: "PL10", name: "Langtang South", stateId: "PL" },
  { lgId: "PL11", name: "Mangu", stateId: "PL" },
  { lgId: "PL12", name: "Mikang", stateId: "PL" },
  { lgId: "PL13", name: "Pankshin", stateId: "PL" },
  { lgId: "PL14", name: "Qua'an Pan", stateId: "PL" },
  { lgId: "PL15", name: "Riyom", stateId: "PL" },
  { lgId: "PL16", name: "Shendam", stateId: "PL" },
  { lgId: "PL17", name: "Wase", stateId: "PL" },
  { lgId: "PL2", name: "Bassa", stateId: "PL" },
  { lgId: "PL3", name: "Bokkos", stateId: "PL" },
  { lgId: "PL4", name: "Jos East", stateId: "PL" },
  { lgId: "PL5", name: "Jos North", stateId: "PL" },
  { lgId: "PL6", name: "Jos South", stateId: "PL" },
  { lgId: "PL7", name: "Kanam", stateId: "PL" },
  { lgId: "PL8", name: "Kanke", stateId: "PL" },
  { lgId: "PL9", name: "Langtang North", stateId: "PL" },
  { lgId: "RV1", name: "Abua/Odual", stateId: "RV" },
  { lgId: "RV10", name: "Emuoha", stateId: "RV" },
  { lgId: "RV11", name: "Etche", stateId: "RV" },
  { lgId: "RV12", name: "Gokana", stateId: "RV" },
  { lgId: "RV13", name: "Ikwerre", stateId: "RV" },
  { lgId: "RV14", name: "Khana", stateId: "RV" },
  { lgId: "RV15", name: "Obio/Akpor", stateId: "RV" },
  { lgId: "RV16", name: "Ogba/Egbema/Ndoni", stateId: "RV" },
  { lgId: "RV17", name: "Ogu/Bolo", stateId: "RV" },
  { lgId: "RV18", name: "Okrika", stateId: "RV" },
  { lgId: "RV19", name: "Omumma", stateId: "RV" },
  { lgId: "RV2", name: "Ahoada East", stateId: "RV" },
  { lgId: "RV20", name: "Opobo/Nkoro", stateId: "RV" },
  { lgId: "RV21", name: "Oyigbo", stateId: "RV" },
  { lgId: "RV22", name: "Port-Harcourt", stateId: "RV" },
  { lgId: "RV23", name: "Tai", stateId: "RV" },
  { lgId: "RV3", name: "Ahoada West", stateId: "RV" },
  { lgId: "RV4", name: "Akuku Toru", stateId: "RV" },
  { lgId: "RV5", name: "Andoni", stateId: "RV" },
  { lgId: "RV6", name: "Asari-Toru", stateId: "RV" },
  { lgId: "RV7", name: "Bonny", stateId: "RV" },
  { lgId: "RV8", name: "Degema", stateId: "RV" },
  { lgId: "RV9", name: "Eleme", stateId: "RV" },
  { lgId: "SK1", name: "Binji", stateId: "SK" },
  { lgId: "SK10", name: "Kebbe", stateId: "SK" },
  { lgId: "SK11", name: "Kware", stateId: "SK" },
  { lgId: "SK12", name: "Rabah", stateId: "SK" },
  { lgId: "SK13", name: "Sabon Birni", stateId: "SK" },
  { lgId: "SK14", name: "Shagari", stateId: "SK" },
  { lgId: "SK15", name: "Silame", stateId: "SK" },
  { lgId: "SK16", name: "Sokoto North", stateId: "SK" },
  { lgId: "SK17", name: "Sokoto South", stateId: "SK" },
  { lgId: "SK18", name: "Tambuwal", stateId: "SK" },
  { lgId: "SK19", name: "Tangaza", stateId: "SK" },
  { lgId: "SK2", name: "Bodinga", stateId: "SK" },
  { lgId: "SK20", name: "Tureta", stateId: "SK" },
  { lgId: "SK21", name: "Wamakko", stateId: "SK" },
  { lgId: "SK22", name: "Wurno", stateId: "SK" },
  { lgId: "SK23", name: "Yabo", stateId: "SK" },
  { lgId: "SK3", name: "Dange Shuni", stateId: "SK" },
  { lgId: "SK4", name: "Gada", stateId: "SK" },
  { lgId: "SK5", name: "Goronyo", stateId: "SK" },
  { lgId: "SK6", name: "Gudu", stateId: "SK" },
  { lgId: "SK7", name: "Gwadabawa", stateId: "SK" },
  { lgId: "SK8", name: "Illela", stateId: "SK" },
  { lgId: "SK9", name: "Isa", stateId: "SK" },
  { lgId: "TR1", name: "Ardo-Kola", stateId: "TR" },
  { lgId: "TR10", name: "Kurmi", stateId: "TR" },
  { lgId: "TR11", name: "Lau", stateId: "TR" },
  { lgId: "TR12", name: "Sardauna", stateId: "TR" },
  { lgId: "TR13", name: "Takum", stateId: "TR" },
  { lgId: "TR14", name: "Ussa", stateId: "TR" },
  { lgId: "TR15", name: "Wukari", stateId: "TR" },
  { lgId: "TR16", name: "Yorro", stateId: "TR" },
  { lgId: "TR17", name: "Zing", stateId: "TR" },
  { lgId: "TR2", name: "Bali", stateId: "TR" },
  { lgId: "TR3", name: "Disputed Areas", stateId: "TR" },
  { lgId: "TR4", name: "Donga", stateId: "TR" },
  { lgId: "TR5", name: "Gashaka", stateId: "TR" },
  { lgId: "TR6", name: "Gassol", stateId: "TR" },
  { lgId: "TR7", name: "Ibi", stateId: "TR" },
  { lgId: "TR8", name: "Jalingo", stateId: "TR" },
  { lgId: "TR9", name: "Karim-Lamido", stateId: "TR" },
  { lgId: "YB1", name: "Bade", stateId: "YB" },
  { lgId: "YB10", name: "Karasuwa", stateId: "YB" },
  { lgId: "YB11", name: "Machina", stateId: "YB" },
  { lgId: "YB12", name: "Nangere", stateId: "YB" },
  { lgId: "YB13", name: "Nguru", stateId: "YB" },
  { lgId: "YB14", name: "Potiskum", stateId: "YB" },
  { lgId: "YB15", name: "Tarmua", stateId: "YB" },
  { lgId: "YB16", name: "Yunusari", stateId: "YB" },
  { lgId: "YB17", name: "Yusufari", stateId: "YB" },
  { lgId: "YB2", name: "Bursari", stateId: "YB" },
  { lgId: "YB3", name: "Damaturu", stateId: "YB" },
  { lgId: "YB4", name: "Fika", stateId: "YB" },
  { lgId: "YB5", name: "Fune", stateId: "YB" },
  { lgId: "YB6", name: "Geidam", stateId: "YB" },
  { lgId: "YB7", name: "Gujba", stateId: "YB" },
  { lgId: "YB8", name: "Gulani", stateId: "YB" },
  { lgId: "YB9", name: "Jakusko", stateId: "YB" },
  { lgId: "ZM1", name: "Anka", stateId: "ZM" },
  { lgId: "ZM10", name: "Maru", stateId: "ZM" },
  { lgId: "ZM11", name: "Shinkafi", stateId: "ZM" },
  { lgId: "ZM12", name: "Talata Mafara", stateId: "ZM" },
  { lgId: "ZM13", name: "Tsafe", stateId: "ZM" },
  { lgId: "ZM14", name: "Zurmi", stateId: "ZM" },
  { lgId: "ZM2", name: "Bakura", stateId: "ZM" },
  { lgId: "ZM3", name: "Birnin Magaji", stateId: "ZM" },
  { lgId: "ZM4", name: "Bukkuyum", stateId: "ZM" },
  { lgId: "ZM5", name: "Bungudu", stateId: "ZM" },
  { lgId: "ZM6", name: "Gummi", stateId: "ZM" },
  { lgId: "ZM7", name: "Gusau", stateId: "ZM" },
  { lgId: "ZM8", name: "Kaura Namoda", stateId: "ZM" },
  { lgId: "ZM9", name: "Maradun", stateId: "ZM" },
];
